-- Migration: Create follows table
CREATE TABLE IF NOT EXISTS follows (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

  follower_id INT NOT NULL ,
  following_id INT NOT NULL ,

  CHECK (follower_id != following_id),
  UNIQUE(follower_id,  following_id)
);

CREATE INDEX IF NOT EXISTS idx_follows_follower_id ON follows(follower_id);
CREATE INDEX IF NOT EXISTS idx_follows_following_id ON follows(following_id);

DROP TRIGGER IF EXISTS update_follows_updated_at ON follows;
CREATE TRIGGER update_follows_updated_at
    BEFORE UPDATE ON follows
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
