-- Migration: Create likes table (polymorphic)
CREATE TABLE IF NOT EXISTS likes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

  user_id INT NOT NULL ,

  likeable_type VARCHAR(50) NOT NULL,
  likeable_id INT NOT NULL,

  UNIQUE(user_id, likeable_type, likeable_id)
);

CREATE INDEX IF NOT EXISTS idx_likes_likeable ON likes(likeable_type, likeable_id);

DROP TRIGGER IF EXISTS update_likes_updated_at ON likes;
CREATE TRIGGER update_likes_updated_at
    BEFORE UPDATE ON likes
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
