-- Migration: Create contributors table (simple audit-style)
CREATE TABLE IF NOT EXISTS contributors (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contribution_type varchar(50) NOT NULL,
  contribution_details jsonb,
  created_at timestamp NOT NULL DEFAULT (now()),
  created_by int,
  updated_at timestamp NOT NULL DEFAULT (now()),
  updated_by int
);

-- indexes for common lookups
CREATE INDEX IF NOT EXISTS idx_contributors_contribution_type ON contributors(contribution_type);
CREATE INDEX IF NOT EXISTS idx_contributors_created_by       ON contributors(created_by);
CREATE INDEX IF NOT EXISTS idx_contributors_updated_by       ON contributors(updated_by);


